[theme]
primaryColor="#124559"
backgroundColor="#e1e5f2"
secondaryBackgroundColor="#bfdbf7"
textColor="#000814"
font="monospace"

[server]
enableXsrfProtection=false



[client]
showSidebarNavigation = false
